//import  HomeAdminPage from "./adminHome/adminHome";
export {ProductsAdminPage} from "./productAdmin/productsAdmin";
export {AddProductAdmin} from './productAdmin/addProduct/addProduct';
export {CartAdminPage} from './cartAdmin/cartAdmin'
export {CommentAdminPage} from './commentsAdmin/commentAdmin'
export {HomeAdminPage} from "./adminHome/adminHome";
export {OrdersAdminPage} from './ordersAdmin/ordrsAdmin';
export {UsersAdminPage} from './usersAdmin/usersAdmin';
export {CategoriesAdmin} from './categoriesAdmin/categoriesAdmin';
export {AddCategoriesAdmin} from './categoriesAdmin/addCatesgories/addCategories';
export {EditCategoryPage} from './categoriesAdmin/editCategory/editCategory';
export {EditProductPage} from './productAdmin/editProducts/editProduct';